apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: account-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: account-mongodb
    spec:
      containers:
      - env:
        - name: INIT_DUMP
          value: account-service-dump.js
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: account_mongodb_password
        ports:
          - containerPort: 27017
        image: afermon/piggymetrics-mongodb
        name: account-mongodb
        resources: {}
      restartPolicy: Always
status: {}
