apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: account-service
  name: account-service
spec:
  ports:
  - name: "6000"
    port: 6000
    targetPort: 6000
  selector:
    project: piggymetrics
    tier: backend
    app: account-service
status:
  loadBalancer: {}
