apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: auth-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: auth-mongodb
    spec:
      containers:
      - image: afermon/piggymetrics-mongodb
        name: auth-mongodb
        env:
          - name: MONGODB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: piggymetrics
                key: auth_mongodb_password
        ports:
          - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
