apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: auth-service
  name: auth-service
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    project: piggymetrics
    tier: infrastructure
    app: auth-service
status:
  loadBalancer: {}
