apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: auth-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: auth-mongodb