apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: auth-service
  name: config
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    project: piggymetrics
    tier: backend
    app: auth-service
status:
  loadBalancer: {}
