apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: frontend
    app: gateway
  name: gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        project: piggymetrics
        tier: frontend
        app: gateway
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        image: afermon/piggymetrics-gateway
        name: gateway
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
