apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: frontend
    app: gateway
  name: gateway
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 4000
    nodePort: 30080
  selector:
    project: piggymetrics
    tier: frontend
    app: gateway
status:
  loadBalancer: {}
