apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: gateway
  name: gateway
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 4000
  selector:
    project: piggymetrics
    tier: infrastructure
    app: gateway
status:
  loadBalancer: {}
