apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: monitoring
  name: monitoring
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 8080
  selector:
    project: piggymetrics
    tier: infrastructure
    app: monitoring
status:
  loadBalancer: {}
