apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: database
    app: notification-mongodb
  name: notification-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:    
        project: piggymetrics
        tier: database
        app: notification-mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: notification_mongodb_password
        ports:
          - containerPort: 27017
        image: afermon/piggymetrics-mongodb
        name: notification-mongodb
        resources: {}
      restartPolicy: Always
status: {}
