apiVersion: v1
kind: Service
metadata:
  name: notification-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: notification-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: notification-mongodb