apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: notification-service
  name: notification-service
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    project: piggymetrics
    tier: backend
    app: notification-service
status:
  loadBalancer: {}
