apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    project: piggymetrics
    tier: infrastructure
    app: rabbitmq
status:
  loadBalancer: {}
