apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: registry
  name: registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: infrastructure
        app: registry
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        image: afermon/piggymetrics-registry
        name: registry
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
status: {}
