apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: registry
  name: registry
spec:
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  selector:
    project: piggymetrics
    tier: infrastructure
    app: registry
status:
  loadBalancer: {}
