apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: statistics-service
  name: statistics-service
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    project: piggymetrics
    tier: backend
    app: statistics-service
status:
  loadBalancer: {}