apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Docker\Kompose\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: turbine-stream-service
  name: turbine-stream-service
spec:
  ports:
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: turbine-stream-service
status:
  loadBalancer: {}
