apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    trier: infrastructure
    app: turbine-stream-service
  name: turbine-stream-service
spec:
  ports:
  - name: http
    port: 8989
    targetPort: 8989
  selector:
    project: piggymetrics
    trier: infrastructure
    app: turbine-stream-service
status:
  loadBalancer: {}
